; Exercise 1.14:
; Draw the tree illustrating the process generated by the count-change procedure
; of 1.2.2 in making change for 11 cents.
; see 1.14.jpg

; What are the orders of growth of the space and number of steps
; used by this process as the amount to be changed increases?
;
; Order of growth in steps:
; n^5


; Order of growth in space:
; O (n) space correlates with the depth of the tree.


(define (count-change amount)
  (cc amount 5 0))

(define (cc amount kinds-of-coins i)
  (display (+ i 1))
  (cond ((= amount 0) 1)
        ((or (< amount 0)
             (= kinds-of-coins 0))
         0)
        (else
         (+ (cc amount (- kinds-of-coins 1) i)
            (cc (- amount (first-denomination
                           kinds-of-coins))
                kinds-of-coins i)))))

(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))


(count-change 11)
(cc 11 5)
